apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5.69
        ports:
        - containerPort: 8080
